blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
   
    path('', HomePageView3.as_view() , name="index"),

    path('download/<int:article_id>', download , name="download"),

    path('test', TestView.as_view(), name="test"),

    path('search', search, name="search"),
    path('article/<int:pk>', ArticleDeteilView.as_view() , name="detail"),
    path('category/<int:category_id>', category_articles, name="category_articles" ),
    path('signer/<int:signer_id>', signer_sounds ),
]

myblog/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls , name="admin"),
    path('', include("blog.urls", namespace="blog" )),
] + static(settings.STATIC_URL,document_root= settings.STATIC_ROOT) +\
     static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT) 

templates/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
</head>
<body>
    
    <h1 class="bg-danger">Help html</h1>
    {% for a in articles %}
    <h1 class="bg-"> {{ a }} </h1>

    {% endfor %}
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        .green{
            color: green;
        }
        .red{
            color: red;
        }
        .color-1{
            color: aqua;
        }
        .color-2{
            color: rgb(27, 30, 185);
        }
        .color-3{
            color: rgb(231, 19, 143);
        }
        .color-4{
            color: rgb(87, 223, 24);
        }
    </style>
    <center>
        {% if company !=  'Andijon Broyler MCHJ' %}
            <h1>Welcome to {{ article.name|truncatechars_html:'3' }}  </h1>
            <h1>Welcome to {{ article.text|truncatewords:'8' }}  </h1>
            <h1> {{ article.text|wordwrap:'8' }}  </h1>
            <h1> {{ article.name|cut:'Sar' }}  </h1>
            <h1> {{ article.text|slugify }}  </h1>
            <h1> {{ article.view|add:"40" }}  </h1>
            <h1> {{ article.text|wordcount }}  </h1>
            <h1> {{ article.text|length }}  </h1>
            <h1> {{ article.text|length_is:"170" }}  </h1>
            <h1> {{ services|first }}  </h1>
            <h1> {{ services|last }}  </h1>
            <h1> {{ services|random }}  </h1>
            <h1> {{ services|slice:":3" }}  </h1>
             
            <ul>
              
                {% for s in services %}
                    <li 
                      class="color-{{ forloop.counter }}"
                    >
                    {{ forloop.counter }}.{{ s }}</li>
                 {% endfor %}
                
            </ul>

            <a href="{% url 'blog:detail' 9 %}">Atricle 1</a>

        {% endif %}
    </center>
    
</body>
</html>